name: Maven Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup JAVA
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    - name: build using maven
      run: mvn clean install

    - name: run-test
      run: mvn test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USER }}/java-app .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: push image to dockerhub
      run: docker push ${{ secrets.DOCKERHUB_USER }}/java-app

    - name: upload jar file
      uses: actions/upload-artifact@v3
      with:
        name: div-jar
        path: ./target/HelloWorld-0.0.1-SNAPSHOT-classes.jar

  download-jar:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: download jar file
        uses: actions/download-artifact@v3
        with:
          name: div-jar

  run-another-workflow:
    needs: [build-and-test,download-jar]
    uses: qliktesting/docker-k8s/.github/workflows/hello-world.yaml@master
